export const data = [
    {
      firstName: "Ahmed",
      lastName: "HM",
      address: "261 Erdman Ford",
      city: "East Daphne",
      state: "Kentucky",
      email: "ahmed.hm@example.com",
      age: 35,
      id: 1,
    },
    {
      firstName: "Karim",
      lastName: "Doe",
      address: "769 Dominic Grove",
      city: "Columbus",
      state: "Ohio",
      email: "karim.doe@example.com",
      age: 28,
      id: 2,
    },
    {
      firstName: "Rim",
      lastName: "Jalel",
      address: "566 Brakus Inlet",
      city: "South Linda",
      state: "West Virginia",
      email: "rim.jalel@example.com",
      age: 42,
      id: 3,
    },
    {
      firstName: "Kevin",
      lastName: "Vandy",
      address: "722 Emie Stream",
      city: "Lincoln",
      state: "Nebraska",
      email: "kevin.vandy@example.com",
      age: 21,
      id: 4,
    },
    {
      firstName: "Joshua",
      lastName: "Rolluffs",
      address: "32188 Larkin Turnpike",
      city: "Omaha",
      state: "Nebraska",
      email: "joshua.rolluffs@example.com",
      age: 29,
      id: 5,
    },
  ];
  
  export const states = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ];
  